# Generated by Django 5.2.9 on 2025-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
