# Generated by Django 5.2.9 on 2025-12-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carimage_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inspectionitem',
            constraint=models.UniqueConstraint(fields=('car', 'subsection', 'name'), name='unique_inspection_item_per_car'),
        ),
    ]
