# Generated by Django 5.2.9 on 2025-12-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_inspectionitem_unique_inspection_item_per_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspec',
            name='unit',
        ),
    ]
