# Generated by Django 5.2.9 on 2025-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_carspec_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carhighlight',
            constraint=models.UniqueConstraint(fields=('car', 'text'), name='unique_car_highlight'),
        ),
    ]
