# Generated by Django 5.2.9 on 2025-12-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carhighlight_unique_car_highlight'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carfeature',
            constraint=models.UniqueConstraint(fields=('car', 'category', 'name'), name='unique_car_feature'),
        ),
        migrations.AddConstraint(
            model_name='carreasontobuy',
            constraint=models.UniqueConstraint(fields=('car', 'title'), name='unique_car_reason_to_buy'),
        ),
        migrations.AddConstraint(
            model_name='carspec',
            constraint=models.UniqueConstraint(fields=('car', 'category', 'label'), name='unique_car_spec'),
        ),
    ]
