# Generated by Django 5.2.9 on 2026-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carfeature_unique_car_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
