# Generated by Django 5.2.10 on 2026-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_availability_status_car_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rto',
            field=models.CharField(blank=True, help_text='RTO code like DL, MH, KA, UP, etc.', max_length=10),
        ),
    ]
