# Generated by Django 5.2.10 on 2026-01-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_rto'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of seats', null=True),
        ),
    ]
