# Generated by Django 5.2.10 on 2026-01-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsection',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of what this category covers', max_length=200),
        ),
        migrations.AddField(
            model_name='inspectionsubsection',
            name='remarks',
            field=models.TextField(blank=True, help_text='General remarks for this subsection'),
        ),
        migrations.CreateModel(
            name='CarInspectionSectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, help_text='Score out of 10 (e.g., 9.6, 8.7)', max_digits=3)),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Overall rating for this section', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes for this section')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_section_scores', to='cars.car')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.inspectionsection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('car', 'section'), name='unique_car_section_score')],
            },
        ),
        migrations.CreateModel(
            name='CarInspectionSubSectionRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, help_text='Car-specific remarks for this subsection')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_subsection_remarks', to='cars.car')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.inspectionsubsection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('car', 'subsection'), name='unique_car_subsection_remarks')],
            },
        ),
    ]
