# Generated by Django 5.2.10 on 2026-01-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_inspectionsection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinspectionsubsectionremarks',
            name='status',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('minor', 'Minor'), ('major', 'Major')], help_text='Status of this subsection', max_length=20),
        ),
    ]
