# Generated by Django 5.2.10 on 2026-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_carinspectionsubsectionremarks_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionsubsection',
            options={'ordering': ['order', 'key']},
        ),
        migrations.AddField(
            model_name='inspectionsubsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the section'),
        ),
    ]
