# Generated by Django 5.2.10 on 2026-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_inspectionsubsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinspectionsectionscore',
            name='status',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('minor', 'Minor'), ('major', 'Major')], help_text='Overall status for this section', max_length=20),
        ),
        migrations.AlterField(
            model_name='carinspectionsectionscore',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes for this section (one line)'),
        ),
    ]
