# Generated by Django 5.2.10 on 2026-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_carinspectionsectionscore_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfeature',
            name='status',
            field=models.CharField(choices=[('flawless', 'Flawless'), ('little_flaw', 'Little flaw'), ('damaged', 'Damaged')], default='flawless', help_text='Status of this feature', max_length=20),
        ),
    ]
