# Generated by Django 5.2.10 on 2026-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_carfeature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='emi',
            field=models.CharField(blank=True, help_text='Monthly EMI display value e.g. ₹13,333/m*', max_length=50),
        ),
    ]
